export interface Cliente {
  nome: string,
  emailUsuarioCadastro: string,
  tipoCliente: string,
  oticaId: string,
  telefone: string, 
  dataNascimento: string,
  razaoSocial: string,
  nomeFantasia: string,
  responsavelLegal: string,
  limiteCredito: string,
  metodoPagamentoPreferido: string,
  indicadorCliente: string,
  preferencias: string,
  observacoes: string,
  ativo: boolean,
  emailCliente: string,
  documento: string,
  enderecoCep: string,
  enderecoLogradouro: string,
  enderecoNumero: string,
  enderecoComplemento: string,
  enderecoBairro: string,
  enderecoCidade: string,
  enderecoEstado: string,
  inscricaoEstadual: string,
 }