export interface Cliente {
  nomeCompleto: string,
  emailUsuarioCadastro: string,
  descricaoTipoCliente: string,
  IdOtica: string,
  telefone: string, 
  dataNascimento: string,
  razaoSocial: string,
  nomeFantasia: string,
  responsavelLegal: string,
  limiteCredito: string,
  metodoPagamentoPreferido: string,
  indicadorCliente: string,
  preferencias: string,
  observacoes: string,
  ativo: boolean,
  email: string,
  documento: string,
  enderecoCep: string,
  enderecoLogradouro: string,
  enderecoNumero: string,
  enderecoComplemento: string,
  enderecoBairro: string,
  enderecoCidade: string,
  enderecoEstado: string,
  inscricaoEstadual: string,
}  